import ChatListSection from "@/components/chat-list";
import Sidebar from "@/components/sidebar/side-bar";
import { Metadata } from "next";
import { ReactNode } from "react";

type Props = {
	children: ReactNode;
};

export const metadata: Metadata = {
	title: "Chat | ChatLoom",
	description: "Generated by create next app",
};

const ConversationLayout = ({ children }: Props) => {
	return (
		<main className="flex sm:flex-row flex-col min-h-screen ">
			<Sidebar />
			<ChatListSection linkItems={[]} />
			{children}
		</main>
	);
};

export default ConversationLayout;
