import UsersSection from "@/components/users-section";
import { Metadata } from "next";
import { redirect } from "next/navigation";
import { ReactNode } from "react";

type Props = {
	children: ReactNode;
};

export const metadata: Metadata = {
	title: "Contacts | ChatLoom",
	description: "Generated by create next app",
};

const ContactsLayout = ({ children }: Props) => {
	return (
		<>
			<UsersSection />
			{children}
		</>
	);
};

export default ContactsLayout;
